{
  parserClass="com.github.danieldeng2.waccplugin.language.WaccParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.danieldeng2.waccplugin.language.psi"
  psiImplPackage="com.github.danieldeng2.waccplugin.language.psi.impl"

  elementTypeHolderClass="com.github.danieldeng2.waccplugin.language.psi.WaccTypes"
  elementTypeClass="com.github.danieldeng2.waccplugin.language.psi.WaccElementType"
  tokenTypeClass="com.github.danieldeng2.waccplugin.language.psi.WaccTokenType"
}

waccFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY